{% set name = "xopt" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cabe5cdbd117bc2fad95e77e77b009cb8bf38f5f4816827ce5dce8248805060c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch >=0.8.2
    - gpytorch
    - pandas
    - pydantic >=2.3
    - orjson

test:
  imports:
    - xopt
  requires:
    - pytest
    - mpi4py
    - dask
    - openssh
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
