{% set name = "xopt" %}
{% set version = "2.6.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a070cd14d784eeffb707a09d283e9414364068355ce6155949ad74fc9f5e624f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch ==0.12
    - gpytorch
    - pandas
    - pydantic >=2.3
    - orjson
    - matplotlib-base

test:
  imports:
    - xopt
  requires:
    - pytest
    - mpi4py
    - dask
    - openssh
    - python {{ python_min }}
  source_files:
    - xopt/tests
  commands:
    - pytest xopt/tests

about:
  home: https://github.com/xopt-org/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
