{% set name = "xopt" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e46373321f042fdc8e2954856e85463536535910f97e0283c9546e169ba00e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.10
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch
    - gpytorch
    - pandas
    - pydantic >=2.3
    - orjson
    - matplotlib

test:
  imports:
    - xopt
  requires:
    - pytest
    - mpi4py
    - dask
    - openssh
  source_files:
    - xopt/tests
  commands:
    - pytest xopt/tests

about:
  home: https://github.com/xopt-org/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
