{% set name = "xopt" %}
{% set version = "2.5.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e6ef0f683c9c22429fbff1e1cd8cd2c740af219474183131b93134cc54afe7b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch >=0.12.0
    - gpytorch
    - pandas
    - pydantic >=2.3
    - orjson
    - matplotlib

test:
  imports:
    - xopt
  requires:
    - pytest
    - mpi4py
    - dask
    - openssh
    - python {{ python_min }}
  source_files:
    - xopt/tests
  commands:
    - pytest xopt/tests

about:
  home: https://github.com/xopt-org/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
