{% set name = "xopt" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b57aa7473bf6389c4e25db457e30d5449755743876ac976b565812daf9b04dc3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch >=0.8.2
    - gpytorch
    - pandas
    - pydantic >=2.3
    - orjson

test:
  imports:
    - xopt
  requires:
    - pytest
    - mpi4py
    - dask
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
